# Model
NUM_CLASSES = 2
IMAGE_SIZE = 128
PATH_MODEL = ""

# Training
NUM_EPOCHES = 10
BATCH_SIZE = 128
SHUFFLE = True
SNAPSHOT_EPOCH = True
SNAPSHOT_STEP = 100
SHOW_METRIC = True

# Classifier
GENRES = []

# Dataset
PATH_TRAINING_DATASET = ""
PATH_VALIDATION_DATASET = ""
PATH_TESTING_DATASET = ""
RATIO_VALIDATION = 0.3
RATIO_TESTING = 0.1

# Songs
PATH_SONGS = ""
